version: '2'
services:
#  hadoop-unit-neo4j:
#    image: hadoop-unit-neo4j
#    ports:
#    - "13533:13533"
  hadoop-unit-neo4j:
    image: neo4j:3.0.4
    ports:
    - "13533:7687"
    environment:
    - NEO4J_AUTH=none
#  hadoop-unit-elasticsearch:
#    image: hadoop-unit-elasticsearch
#    ports:
#    - "14433:14433"
#    - "14533:14533"
  hadoop-unit-elasticsearch:
    image: elasticsearch:5.0.0-alpha4
    ports:
    - "14433:9200"
    - "14533:9300"
    security_opt:
    - seccomp:unconfined
    environment:
    - ES_JAVA_OPTS=-Xms1g -Xmx1g
#  hadoop-unit-cassandra:
#    image: hadoop-unit-cassandra
#    ports:
#    - "13433:13433"
  hadoop-unit-cassandra:
    image: cassandra:3.7
    ports:
    - "13433:9042"
#  hadoop-unit-mongodb:
#    image: hadoop-unit-mongodb
#    ports:
#    - "13333:13333"
  hadoop-unit-mongodb:
    image: mongo:3.3.11
    ports:
    - "13333:27017"
  hadoop-unit-hbase:
    image: hadoop-unit-hbase
    ports:
    - "25111:25111"
#    - "30000-45000"
    depends_on:
      - hadoop-unit-zookeeper
      - hadoop-unit-hdfs
  hadoop-unit-solrcloud:
    image: hadoop-unit-solrcloud
    ports:
    - "8983:8983"
    depends_on:
      - hadoop-unit-zookeeper
  hadoop-unit-hive:
    image: hadoop-unit-hive
    ports:
    - "20102:20102"
    - "20103:20103"
    depends_on:
      - hadoop-unit-hdfs
      - hadoop-unit-zookeeper
  hadoop-unit-oozie:
    image: hadoop-unit-oozie
    ports:
    - "20113:20113"
    depends_on:
      - hadoop-unit-zookeeper
      - hadoop-unit-hdfs
      - hadoop-unit-hive
    volumes:
    - /home/khanh/github:/oozie
  hadoop-unit-hdfs:
    image: hadoop-unit-hdfs
    ports:
    - "20112:20112"
    - "50070:50070"
#  hadoop-unit-kafka:
#    image: hadoop-unit-kafka
#    ports:
#    - "9092:9092"
#    depends_on:
#      - hadoop-unit-zookeeper
  hadoop-unit-kafka:
    image: ches/kafka
    ports:
    - "20111:9092"
    environment:
    - ZOOKEEPER_IP=hadoop-unit-zookeeper
    - ZOOKEEPER_PORT=22010
    depends_on:
    - hadoop-unit-zookeeper
  hadoop-unit-zookeeper:
    image: hadoop-unit-zookeeper
    ports:
    - "22010:22010"
